export const inputArr = [
  { inputName: "Title", idAndKey: "title", isReq: true },
  { inputName: "Sub Title", idAndKey: "subTitle", isReq: true },
  { inputName: "Description", idAndKey: "description", isReq: true },
  { inputName: "State", idAndKey: "state", isReq: false },
  { inputName: "Country", idAndKey: "country", isReq: true },
  { inputName: "City", idAndKey: "city", isReq: true },
  { inputName: "Street", idAndKey: "street", isReq: true },
  { inputName: "House Number", idAndKey: "houseNumber", isReq: true },
  { inputName: "ZIP Code", idAndKey: "zipCode", isReq: false },
  { inputName: "Phone", idAndKey: "phone", isReq: true },
  { inputName: "Email", idAndKey: "email", isReq: true },
  { inputName: "Web Page URL", idAndKey: "web", isReq: false },
  { inputName: "Image URL", idAndKey: "url", isReq: false },
  { inputName: "Image Alt", idAndKey: "alt", isReq: false },
];
